### ISSUE TITLE
Please Add LICENSE file

### ISSUE THREAD

**Issue by hnakamur** [cevaris/ordered_map#1]
Thanks for sharing a nice library!
Could you add a LICENSE file?

The following page might help for choosing a license.
[Choosing an open source license doesn’t need to be scary - Choose a License](http://choosealicense.com/)

Thanks!

**Comment by cevaris** [comment]
Added.
https://github.com/cevaris/ordered_map/commit/d28f6fb28d02d657a4163a9bc07a989b12a1c32c
