### ISSUE TITLE
OrderedMap delete memory leak : not delete mapper

### ISSUE THREAD

**Issue by newzai** [cevaris/ordered_map#11]
call OrderedMap Delete key, value from store, but not delete mapper

**Comment by cevaris** [comment]
good day @newzai 

Can you provide some code example of the issue you are having. 

Having a hard time understanding the issue. Sounds like there is some memory leak on deletes?? Can you please clarify? 

Thanks.

**Comment by newzai** [comment]
now code for Delete 
``` go
func (om *OrderedMap) Delete(key interface{}) {
	_, ok := om.store[key]
	if ok {
		delete(om.store, key)
	}
	root, rootFound := om.mapper[key]
	if rootFound {
		prev := root.Prev
		next := root.Next
		prev.Next = next
		next.Prev = prev
	}
}
```

my fix code for Delete 
``` go
func (om *OrderedMap) Delete(key interface{}) {
	_, ok := om.store[key]
	if ok {
		delete(om.store, key)
	}
	root, rootFound := om.mapper[key]
	if rootFound {
		prev := root.Prev
		next := root.Next
		prev.Next = next
		next.Prev = prev
		delete(om.mapper, key)  //   如果不调用，mapper对象存在内存泄漏 
	}
}
```

**Comment by cevaris** [comment]
Thanks for posting @newzai ! reviewing the issue.

**Comment by cevaris** [comment]
Thanks @newzai 
Fixed https://github.com/cevaris/ordered_map/commit/01ce2b16ad4f7522692d9af8337722216a1038bb
Thanks for finding and proposing solution. 
Please let me know if there was anything else 👍
