### ISSUE TITLE
goroutine leak on early termination of iteration

### ISSUE THREAD

**Issue by campbellr** [cevaris/ordered_map#4]
I'm pretty sure that the current implementation of `OrderedMap.Iter` will result in a goroutine leak if the user stops iteration before consuming all values from the channel (either explicitly via a `break` or `return`, or via a `panic`).

The easiest solution I can think of to solve this is return two values, the iteration channel and a "done" channel.

For example (completely contrived):

```go
iter, done := om.Iter()
for kv := range iter {
    if kv.Value.(string) == "foobar" {
        close(done)
        return kv
    }
}

```

Unfortunately this makes the API a bit less pleasant...

**Comment by cevaris** [comment]
Thanks @campbellr, correct we are leaking goroutines. Let me know what you think about PR #6 which deprecates channel based iterators for closure based ones.

**Comment by campbellr** [comment]
@cevaris Sorry for taking so long to reply, but that looks good to me. Thanks!

Looks like this can be closed now.
