### ISSUE TITLE
Question: Why the deprecation of Iter()?

### ISSUE THREAD

**Issue by josephschorr** [cevaris/ordered_map#9]
I see the addition of the `IterFunc()` method, as well as the deprecation notice on `Iter()`. However, I'm curious why `Iter()` is being deprecated, as its removal means I'll need a wrapper function to iterate over the `ordered_map` from within a Golang template, whose `range` keyword requires an array, slice or channel.

**Comment by cevaris** [comment]
Good day @josephschorr 

Have you seen https://github.com/cevaris/ordered_map/issues/4

`Iter()` leaks goroutines for unfinished iterations. And we wanted to discourage its use. 

It does seem golang templates are a valid use-case for `Iter()` since the templates fully traverses the map.

But you are right, you should be able to wrap it it? Something like the following?

```
func Iter(om *OrderedMap) <-chan *KVPair {
	keys := make(chan *KVPair)
	go func() {
		defer close(keys)
                iter := om.IterFunc()
                for kv, ok := iter(); ok; kv, ok = iter() {
                    keys <- kv
                }	
        }()
	return keys
}

om := ordered_map.NewOrderedMap()
// add some data to om
for kv := range Iter(om) {
    fmt.Println(kv, kv.Key, kv.Value)
}
```

**Comment by josephschorr** [comment]
Hi @cevaris:

I apologize for missing #4; that makes perfect sense. I'll definitely use your suggestion to wrap in my own template call. Do you see any benefit in having an explicitly marked copy of this method in the library itself for other users that might call it from a template? Something like `IterForTemplate(...)`?

**Comment by cevaris** [comment]
True, but `IterForTemplate()` is more of a apps-specific/util method, would rather leave out for now. 

Perhaps we can add a new method `UnsafeIter()` method and move some logic around to keep the `Iter()` deprecated message in.

```
func (om *OrderedMap) Iter() <-chan *KVPair {
	println("Iter() method is deprecated!. Use IterFunc() instead.")
	return om.UnsafeIter()
}

func (om *OrderedMap) UnsafeIter() <-chan *KVPair {
	// Same logic as Iter()
	keys := make(chan *KVPair)
	go func() {
		defer close(keys)
		var curr *node
		root := om.root
		curr = root.Next
		for curr != root {
			v, _ := om.store[curr.Value]
			keys <- &KVPair{curr.Value, v}
			curr = curr.Next
		}
	}()
	return keys
} 
```

That way
- `Iter()` is kept deprecated
- No need to create a new wrapper `IterForTemplate()`
- Still expose an `range`-able iterable, but it is clear that you should probably not use it
- And most importantly, backwards compatiable

**Comment by josephschorr** [comment]
@cevaris: Awesome! Thanks for adding it in for me.
